<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTz0VeDP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTz0VeDP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTz0VeDP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTz0VeDP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTz0VeDP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Tz0VeDP',
    'container.build_id' => '70c897e6',
    'container.build_time' => 1556841372,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTz0VeDP');
