<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFG7wArO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFG7wArO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFG7wArO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFG7wArO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFG7wArO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FG7wArO',
    'container.build_id' => '501de62f',
    'container.build_time' => 1557082656,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFG7wArO');
