<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJJauw7y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJJauw7y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJJauw7y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJJauw7y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJJauw7y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JJauw7y',
    'container.build_id' => 'd4baa9d9',
    'container.build_time' => 1556407376,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJJauw7y');
